const data = {
  products: [
    {
      product_id: "1",
      product_name: "Purple Basil",
      product_image: "/images/herb1.png",
      description: "The purple basil can be used as you would use basil",
      category: "herbs",
      price: 120,
      StockQuantity: 50,
      rating: 4.0,
      no_of_reviews: 39,
    },
    {
      product_id: "2",
      product_name: "Chervil",
      product_image: "/images/herb2.png",
      description:
        "This herb can be used with eggs, vegetable dishes & marinades",
      category: "herbs",
      price: 200,
      StockQuantity: 20,
      rating: 4.5,
      no_of_reviews: 304,
    },
    {
      product_id: "3",
      product_name: "Pineapple Sage",
      product_image: "/images/herb3.png",
      description: "This can be used as fruit salads, cocktails and garnish",
      category: "herbs",
      price: 180,
      StockQuantity: 0,
      rating: 3.5,
      no_of_reviews: 78,
    },
    {
      product_id: "4",
      product_name: "Sage",
      product_image: "/images/herb4.png",
      description: "This can be used to prepare pork, bacon and potatoes",
      category: "herbs",
      price: 270,
      StockQuantity: 5,
      rating: 4.0,
      no_of_reviews: 30,
    },
    {
      product_id: "5",
      product_name: "Coriander",
      product_image: "/images/herb5.png",
      description:
        "Use the root, stem and leaves. Very good in curries, salads and Asian dishes",
      category: "herbs",
      price: 150,
      StockQuantity: 32,
      rating: 4.0,
      no_of_reviews: 380,
    },
    {
      product_id: "6",
      product_name: "Vietnamese Mint",
      product_image: "/images/herb6.png",
      description:
        "Not a real mint but very spicy, lightly peppery herb used in Asian cuisine",
      category: "herbs",
      price: 250,
      StockQuantity: 9,
      rating: 5.0,
      no_of_reviews: 48,
    },
  ],
};
export default data;
